'use strict';

const CIVS = {
  britons: {
    name: 'Britons',
    color: '#2277ff',
    bonuses: {
      shepherdSpeedBonus: 1.25,
      tcWoodCostMultiplier: 0.5,
    },
    uniqueUnit: 'longbowman',
    uniqueUnitName: 'Longbowman',
    teamBonus: 'Archery Ranges 20% faster',
    description: 'Shepherds 25% faster, TC -50% wood',
  },
  franks: {
    name: 'Franks',
    color: '#ff4422',
    bonuses: {
      cavalryHPBonus: 1.20,
      farmUpgradesFree: true,
    },
    uniqueUnit: 'throwing_axeman',
    uniqueUnitName: 'Throwing Axeman',
    teamBonus: 'Knights +2 line of sight',
    description: 'Cavalry +20% HP, farm upgrades free',
  },
};

// Unit stat definitions
const UNIT_DEFS = {
  villager: {
    name: 'Villager',
    icon: '&#128119;',
    hp: 25, attack: 3, meleeArmor: 0, pierceArmor: 0,
    range: 1, speed: 1.2, attackSpeed: 2.0, los: 4,
    carryCapacity: 10,
    canGather: true, canBuild: true,
    age: 0,
    cost: { food: 50 },
    trainTime: 25,
    color: '#aabbff',
    shape: 'circle',
    description: 'Gathers resources, constructs buildings.',
  },
  militia: {
    name: 'Militia',
    icon: '&#9876;',
    hp: 40, attack: 4, meleeArmor: 0, pierceArmor: 0,
    range: 1, speed: 1.0, attackSpeed: 2.0, los: 4,
    age: 0, cost: { food: 60 },
    trainTime: 21,
    color: '#ff6644',
    shape: 'square',
    description: 'Basic infantry unit.',
  },
  man_at_arms: {
    name: 'Man-at-Arms',
    icon: '&#9876;',
    hp: 60, attack: 6, meleeArmor: 1, pierceArmor: 0,
    range: 1, speed: 1.0, attackSpeed: 2.0, los: 4,
    age: 2, cost: { food: 60, gold: 20 },
    trainTime: 21,
    color: '#ff4422',
    shape: 'square',
    description: 'Upgraded infantry unit.',
    upgradesFrom: 'militia',
  },
  archer: {
    name: 'Archer',
    icon: '&#127996;',
    hp: 30, attack: 4, meleeArmor: 0, pierceArmor: 0,
    range: 5, speed: 1.2, attackSpeed: 2.0, los: 6,
    age: 1, cost: { wood: 25, gold: 45 },
    trainTime: 35,
    color: '#ffaa00',
    shape: 'diamond',
    description: 'Ranged unit, effective vs infantry.',
    projectile: true,
  },
  crossbowman: {
    name: 'Crossbowman',
    icon: '&#127996;',
    hp: 35, attack: 5, meleeArmor: 0, pierceArmor: 1,
    range: 6, speed: 1.0, attackSpeed: 2.5, los: 7,
    age: 2, cost: { wood: 25, gold: 45 },
    trainTime: 27,
    color: '#ff8800',
    shape: 'diamond',
    description: 'Upgraded archer, more damage and range.',
    upgradesFrom: 'archer',
    projectile: true,
  },
  scout: {
    name: 'Scout Cavalry',
    icon: '&#128014;',
    hp: 45, attack: 3, meleeArmor: 0, pierceArmor: 2,
    range: 1, speed: 2.2, attackSpeed: 2.0, los: 6,
    age: 0, cost: { food: 80 },
    trainTime: 30,
    color: '#22bbff',
    shape: 'horse',
    description: 'Fast scout, weak in combat.',
  },
  knight: {
    name: 'Knight',
    icon: '&#9816;',
    hp: 100, attack: 10, meleeArmor: 2, pierceArmor: 2,
    range: 1, speed: 1.8, attackSpeed: 2.0, los: 5,
    age: 2, cost: { food: 60, gold: 75 },
    trainTime: 30,
    color: '#00aaff',
    shape: 'horse',
    description: 'Heavy cavalry, strong vs archers.',
  },
  longbowman: {
    name: 'Longbowman',
    icon: '&#127996;',
    hp: 35, attack: 6, meleeArmor: 0, pierceArmor: 0,
    range: 7, speed: 1.0, attackSpeed: 2.0, los: 8,
    age: 2, cost: { wood: 35, gold: 45 },
    trainTime: 25,
    color: '#cc9900',
    shape: 'diamond',
    description: 'Britons unique unit. Extra range.',
    civOnly: 'britons',
    projectile: true,
  },
  throwing_axeman: {
    name: 'Throwing Axeman',
    icon: '&#9876;',
    hp: 70, attack: 7, meleeArmor: 0, pierceArmor: 0,
    range: 3, speed: 1.0, attackSpeed: 2.0, los: 5,
    age: 2, cost: { food: 55, gold: 25 },
    trainTime: 17,
    color: '#ff6600',
    shape: 'square',
    description: 'Franks unique unit. Ranged infantry.',
    civOnly: 'franks',
    projectile: true,
  },
  battering_ram: {
    name: 'Battering Ram',
    icon: '&#128641;',
    hp: 200, attack: 40, meleeArmor: 5, pierceArmor: 5,
    range: 1, speed: 0.6, attackSpeed: 5.0, los: 3,
    age: 2, cost: { wood: 160, gold: 75 },
    trainTime: 56,
    color: '#885533',
    shape: 'rect',
    description: 'Siege unit, anti-building.',
    vsBuildingBonus: 5,
  },
  mangonel: {
    name: 'Mangonel',
    icon: '&#128641;',
    hp: 50, attack: 40, meleeArmor: 0, pierceArmor: 6,
    range: 7, minRange: 3, speed: 0.5, attackSpeed: 6.0, los: 7,
    age: 2, cost: { wood: 160, gold: 135 },
    trainTime: 46,
    color: '#664422',
    shape: 'rect',
    description: 'Siege unit, area damage.',
    aoe: 1.5,
    projectile: true,
  },

  // === New units ===

  spearman: {
    name: 'Spearman',
    icon: '&#9876;',
    hp: 45, attack: 3, meleeArmor: 0, pierceArmor: 0,
    range: 1, speed: 1.0, attackSpeed: 3.0, los: 4,
    age: 1, cost: { food: 35, wood: 25 },
    trainTime: 22,
    color: '#dd5533',
    shape: 'square',
    description: 'Anti-cavalry infantry.',
    vsCavalryBonus: 15,
  },
  pikeman: {
    name: 'Pikeman',
    icon: '&#9876;',
    hp: 55, attack: 4, meleeArmor: 0, pierceArmor: 0,
    range: 1, speed: 1.0, attackSpeed: 3.0, los: 4,
    age: 2, cost: { food: 35, wood: 25 },
    trainTime: 22,
    color: '#cc4422',
    shape: 'square',
    description: 'Upgraded spearman.',
    upgradesFrom: 'spearman',
    vsCavalryBonus: 22,
  },
  skirmisher: {
    name: 'Skirmisher',
    icon: '&#127996;',
    hp: 30, attack: 2, meleeArmor: 0, pierceArmor: 3,
    range: 4, speed: 1.2, attackSpeed: 3.0, los: 6,
    age: 1, cost: { food: 25, wood: 35 },
    trainTime: 22,
    color: '#88bb44',
    shape: 'diamond',
    description: 'Anti-archer ranged unit.',
    projectile: true,
    vsArcherBonus: 3,
  },
  cavalry_archer: {
    name: 'Cavalry Archer',
    icon: '&#128014;',
    hp: 50, attack: 6, meleeArmor: 0, pierceArmor: 0,
    range: 4, speed: 1.8, attackSpeed: 2.0, los: 5,
    age: 2, cost: { wood: 40, gold: 60 },
    trainTime: 34,
    color: '#cc8800',
    shape: 'horse',
    description: 'Mounted ranged unit.',
    projectile: true,
  },
  light_cavalry: {
    name: 'Light Cavalry',
    icon: '&#128014;',
    hp: 60, attack: 7, meleeArmor: 0, pierceArmor: 2,
    range: 1, speed: 2.2, attackSpeed: 2.0, los: 8,
    age: 2, cost: { food: 80 },
    trainTime: 30,
    color: '#33ccff',
    shape: 'horse',
    description: 'Upgraded scout cavalry.',
    upgradesFrom: 'scout',
  },
  camel_rider: {
    name: 'Camel Rider',
    icon: '&#128014;',
    hp: 100, attack: 6, meleeArmor: 0, pierceArmor: 0,
    range: 1, speed: 1.8, attackSpeed: 2.0, los: 5,
    age: 2, cost: { food: 55, gold: 60 },
    trainTime: 22,
    color: '#ddaa55',
    shape: 'camel',
    description: 'Anti-cavalry mounted unit.',
    vsCavalryBonus: 9,
  },
  monk: {
    name: 'Monk',
    icon: '&#9770;',
    hp: 30, attack: 0, meleeArmor: 0, pierceArmor: 0,
    range: 9, speed: 0.7, attackSpeed: 0, los: 11,
    age: 2, cost: { gold: 100 },
    trainTime: 51,
    color: '#ffdd88',
    shape: 'circle',
    description: 'Heals friendly units.',
    canHeal: true,
    healRate: 1.5,
  },
  scorpion: {
    name: 'Scorpion',
    icon: '&#128641;',
    hp: 40, attack: 12, meleeArmor: 0, pierceArmor: 7,
    range: 7, speed: 0.5, attackSpeed: 3.6, los: 7,
    age: 2, cost: { wood: 75, gold: 75 },
    trainTime: 30,
    color: '#775544',
    shape: 'rect',
    description: 'Anti-unit siege weapon.',
    projectile: true,
    aoe: 0.5,
  },
  trebuchet: {
    name: 'Trebuchet',
    icon: '&#128641;',
    hp: 150, attack: 200, meleeArmor: 2, pierceArmor: 8,
    range: 16, minRange: 5, speed: 0.3, attackSpeed: 10.0, los: 18,
    age: 2, cost: { wood: 200, gold: 200 },
    trainTime: 50,
    color: '#886644',
    shape: 'rect',
    description: 'Long-range anti-building siege.',
    projectile: true,
    vsBuildingBonus: 200,
    aoe: 0.5,
  },

  // === Imperial Age units ===

  champion: {
    name: 'Champion',
    icon: '&#9876;',
    hp: 70, attack: 13, meleeArmor: 1, pierceArmor: 1,
    range: 1, speed: 1.0, attackSpeed: 2.0, los: 4,
    age: 3, cost: { food: 60, gold: 20 },
    trainTime: 21,
    color: '#ff2200',
    shape: 'square',
    description: 'Elite infantry unit.',
  },
  arbalester: {
    name: 'Arbalester',
    icon: '&#127996;',
    hp: 40, attack: 6, meleeArmor: 0, pierceArmor: 1,
    range: 7, speed: 1.0, attackSpeed: 2.5, los: 8,
    age: 3, cost: { wood: 25, gold: 45 },
    trainTime: 27,
    color: '#ff6600',
    shape: 'diamond',
    description: 'Elite crossbowman.',
    upgradesFrom: 'crossbowman',
    projectile: true,
  },
  paladin: {
    name: 'Paladin',
    icon: '&#9816;',
    hp: 180, attack: 14, meleeArmor: 2, pierceArmor: 3,
    range: 1, speed: 1.8, attackSpeed: 2.0, los: 5,
    age: 3, cost: { food: 60, gold: 75 },
    trainTime: 30,
    color: '#0066ff',
    shape: 'horse',
    description: 'Elite knight.',
  },
  bombard_cannon: {
    name: 'Bombard Cannon',
    icon: '&#128641;',
    hp: 80, attack: 40, meleeArmor: 2, pierceArmor: 5,
    range: 12, minRange: 5, speed: 0.5, attackSpeed: 8.0, los: 14,
    age: 3, cost: { wood: 225, gold: 225 },
    trainTime: 56,
    color: '#554433',
    shape: 'rect',
    description: 'Heavy siege cannon.',
    projectile: true,
    aoe: 1.0,
  },
};

// Building stat definitions
const BUILDING_DEFS = {
  town_center: {
    name: 'Town Center',
    icon: '&#127968;',
    hp: 2400, size: 4,
    cost: { wood: 275 },
    buildTime: 150,
    age: 0,
    produces: ['villager'],
    dropOff: ['food', 'wood', 'gold', 'stone'],
    popCap: 5,
    los: 8,
    color: '#8866aa',
    description: 'Main building. Train villagers, age up.',
  },
  house: {
    name: 'House',
    icon: '&#127968;',
    hp: 550, size: 2,
    cost: { wood: 25 },
    buildTime: 25,
    age: 0,
    popCap: 5,
    color: '#775533',
    description: 'Increases population cap by 5.',
  },
  mill: {
    name: 'Mill',
    icon: '&#127806;',
    hp: 900, size: 3,
    cost: { wood: 100 },
    buildTime: 40,
    age: 0,
    dropOff: ['food'],
    color: '#aaaa44',
    description: 'Food drop-off point.',
  },
  lumber_camp: {
    name: 'Lumber Camp',
    icon: '&#129683;',
    hp: 600, size: 2,
    cost: { wood: 100 },
    buildTime: 35,
    age: 0,
    dropOff: ['wood'],
    color: '#665533',
    description: 'Wood drop-off point.',
  },
  mining_camp: {
    name: 'Mining Camp',
    icon: '&#9935;',
    hp: 600, size: 2,
    cost: { gold: 0, wood: 100 },
    buildTime: 35,
    age: 0,
    dropOff: ['gold', 'stone'],
    color: '#888877',
    description: 'Gold and stone drop-off point.',
  },
  farm: {
    name: 'Farm',
    icon: '&#127807;',
    hp: 360, size: 3,
    cost: { wood: 60 },
    buildTime: 15,
    age: 0,
    foodSource: true,
    foodRate: 0.3, // food per second while worked
    color: '#88aa44',
    description: 'Provides slow food when worked by villager.',
  },
  barracks: {
    name: 'Barracks',
    icon: '&#9876;',
    hp: 1200, size: 3,
    cost: { wood: 175 },
    buildTime: 50,
    age: 0,
    produces: ['militia', 'man_at_arms', 'spearman', 'pikeman', 'champion'],
    color: '#994433',
    description: 'Train infantry units.',
  },
  archery_range: {
    name: 'Archery Range',
    icon: '&#127996;',
    hp: 1200, size: 3,
    cost: { wood: 175 },
    buildTime: 50,
    age: 1,
    produces: ['archer', 'crossbowman', 'longbowman', 'skirmisher', 'cavalry_archer', 'arbalester'],
    color: '#998833',
    description: 'Train archer units.',
  },
  stable: {
    name: 'Stable',
    icon: '&#128014;',
    hp: 1500, size: 4,
    cost: { wood: 175 },
    buildTime: 50,
    age: 1,
    produces: ['scout', 'knight', 'light_cavalry', 'camel_rider', 'paladin'],
    color: '#885522',
    description: 'Train cavalry units.',
  },
  castle: {
    name: 'Castle',
    icon: '&#9962;',
    hp: 4800, size: 4,
    cost: { stone: 650 },
    buildTime: 200,
    age: 2,
    produces: ['longbowman', 'throwing_axeman', 'trebuchet'],
    los: 10,
    attackRange: 8,
    attackDamage: 11,
    attackSpeed: 2.0,
    color: '#998888',
    description: 'Fortress. Train unique units.',
  },
  siege_workshop: {
    name: 'Siege Workshop',
    icon: '&#128641;',
    hp: 1500, size: 3,
    cost: { wood: 200 },
    buildTime: 40,
    age: 2,
    produces: ['battering_ram', 'mangonel', 'scorpion', 'bombard_cannon'],
    color: '#776655',
    description: 'Train siege weapons.',
  },
  monastery: {
    name: 'Monastery',
    icon: '&#9770;',
    hp: 1500, size: 3,
    cost: { wood: 175 },
    buildTime: 40,
    age: 2,
    produces: ['monk'],
    color: '#997799',
    description: 'Train monks.',
  },
  market: {
    name: 'Market',
    icon: '&#127981;',
    hp: 1200, size: 3,
    cost: { wood: 175 },
    buildTime: 60,
    age: 1,
    dropOff: ['gold'],
    color: '#aa8855',
    description: 'Gold drop-off point.',
  },
  dock: {
    name: 'Dock',
    icon: '&#9875;',
    hp: 1800, size: 3,
    cost: { wood: 150 },
    buildTime: 35,
    age: 0,
    dropOff: ['food'],
    color: '#557799',
    description: 'Food drop-off near water.',
  },
  palisade_wall: {
    name: 'Palisade Wall',
    icon: '&#9632;',
    hp: 250, size: 1,
    cost: { wood: 2 },
    buildTime: 6,
    age: 0,
    color: '#886644',
    description: 'Cheap wooden wall.',
  },
  gate: {
    name: 'Gate',
    icon: '&#9632;',
    hp: 2500, size: 1,
    cost: { stone: 30 },
    buildTime: 70,
    age: 1,
    color: '#999999',
    description: 'Strong wall segment.',
  },
  tower: {
    name: 'Watch Tower',
    icon: '&#9961;',
    hp: 1000, size: 2,
    cost: { wood: 125, stone: 100 },
    buildTime: 80,
    age: 1,
    attackRange: 7,
    attackDamage: 5,
    attackSpeed: 2.0,
    los: 8,
    color: '#997755',
    description: 'Defensive tower.',
  },
  wall: {
    name: 'Stone Wall',
    icon: '&#9632;',
    hp: 1800, size: 1,
    cost: { stone: 5 },
    buildTime: 10,
    age: 1,
    color: '#aaaaaa',
    description: 'Defensive wall segment.',
  },
};

// Age definitions
const AGE_DEFS = [
  {
    name: 'Dark Age',
    advanceCost: null,
    advanceTime: 0,
  },
  {
    name: 'Feudal Age',
    advanceCost: { food: 500 },
    advanceTime: 130,
  },
  {
    name: 'Castle Age',
    advanceCost: { food: 800, gold: 200 },
    advanceTime: 160,
  },
  {
    name: 'Imperial Age',
    advanceCost: { food: 1000, gold: 800 },
    advanceTime: 190,
  },
];

// Apply civ bonuses to unit stats
function applyStatBonuses(unitType, stats, civName) {
  const civ = CIVS[civName];
  if (!civ) return stats;
  const s = Object.assign({}, stats);

  if (civName === 'franks' && (unitType === 'scout' || unitType === 'knight')) {
    s.hp = Math.round(s.hp * civ.bonuses.cavalryHPBonus);
  }
  return s;
}
