'use strict';

const CIVS = {
  britons: {
    name: 'Britons',
    color: '#2277ff',
    bonuses: {
      shepherdSpeedBonus: 1.25,
      tcWoodCostMultiplier: 0.5,
    },
    uniqueUnit: 'longbowman',
    uniqueUnitName: 'Longbowman',
    teamBonus: 'Archery Ranges 20% faster',
    description: 'Shepherds 25% faster, TC -50% wood',
  },
  franks: {
    name: 'Franks',
    color: '#ff4422',
    bonuses: {
      cavalryHPBonus: 1.20,
      farmUpgradesFree: true,
    },
    uniqueUnit: 'throwing_axeman',
    uniqueUnitName: 'Throwing Axeman',
    teamBonus: 'Knights +2 line of sight',
    description: 'Cavalry +20% HP, farm upgrades free',
  },
};

// Unit stat definitions
const UNIT_DEFS = {
  villager: {
    name: 'Villager',
    icon: '&#128119;',
    hp: 25, attack: 3, meleeArmor: 0, pierceArmor: 0,
    range: 1, speed: 1.2, attackSpeed: 2.0, los: 4,
    carryCapacity: 10,
    canGather: true, canBuild: true,
    age: 0,
    cost: { food: 50 },
    trainTime: 25,
    color: '#aabbff',
    shape: 'circle',
    description: 'Gathers resources, constructs buildings.',
  },
  militia: {
    name: 'Militia',
    icon: '&#9876;',
    hp: 40, attack: 4, meleeArmor: 0, pierceArmor: 0,
    range: 1, speed: 1.0, attackSpeed: 2.0, los: 4,
    age: 1, cost: { food: 60 },
    trainTime: 21,
    color: '#ff6644',
    shape: 'square',
    description: 'Basic infantry unit.',
  },
  man_at_arms: {
    name: 'Man-at-Arms',
    icon: '&#9876;',
    hp: 60, attack: 6, meleeArmor: 1, pierceArmor: 0,
    range: 1, speed: 1.0, attackSpeed: 2.0, los: 4,
    age: 2, cost: { food: 60, gold: 20 },
    trainTime: 21,
    color: '#ff4422',
    shape: 'square',
    description: 'Upgraded infantry unit.',
    upgradesFrom: 'militia',
  },
  archer: {
    name: 'Archer',
    icon: '&#127996;',
    hp: 30, attack: 4, meleeArmor: 0, pierceArmor: 0,
    range: 5, speed: 1.2, attackSpeed: 2.0, los: 6,
    age: 1, cost: { wood: 25, gold: 45 },
    trainTime: 35,
    color: '#ffaa00',
    shape: 'diamond',
    description: 'Ranged unit, effective vs infantry.',
    projectile: true,
  },
  crossbowman: {
    name: 'Crossbowman',
    icon: '&#127996;',
    hp: 35, attack: 5, meleeArmor: 0, pierceArmor: 1,
    range: 6, speed: 1.0, attackSpeed: 2.5, los: 7,
    age: 2, cost: { wood: 25, gold: 45 },
    trainTime: 27,
    color: '#ff8800',
    shape: 'diamond',
    description: 'Upgraded archer, more damage and range.',
    upgradesFrom: 'archer',
    projectile: true,
  },
  scout: {
    name: 'Scout Cavalry',
    icon: '&#128014;',
    hp: 45, attack: 3, meleeArmor: 0, pierceArmor: 2,
    range: 1, speed: 2.2, attackSpeed: 2.0, los: 6,
    age: 0, cost: { food: 80 },
    trainTime: 30,
    color: '#22bbff',
    shape: 'horse',
    description: 'Fast scout, weak in combat.',
  },
  knight: {
    name: 'Knight',
    icon: '&#9816;',
    hp: 100, attack: 10, meleeArmor: 2, pierceArmor: 2,
    range: 1, speed: 1.8, attackSpeed: 2.0, los: 5,
    age: 2, cost: { food: 60, gold: 75 },
    trainTime: 30,
    color: '#00aaff',
    shape: 'horse',
    description: 'Heavy cavalry, strong vs archers.',
  },
  longbowman: {
    name: 'Longbowman',
    icon: '&#127996;',
    hp: 35, attack: 6, meleeArmor: 0, pierceArmor: 0,
    range: 7, speed: 1.0, attackSpeed: 2.0, los: 8,
    age: 2, cost: { wood: 35, gold: 45 },
    trainTime: 25,
    color: '#cc9900',
    shape: 'diamond',
    description: 'Britons unique unit. Extra range.',
    civOnly: 'britons',
    projectile: true,
  },
  throwing_axeman: {
    name: 'Throwing Axeman',
    icon: '&#9876;',
    hp: 70, attack: 7, meleeArmor: 0, pierceArmor: 0,
    range: 3, speed: 1.0, attackSpeed: 2.0, los: 5,
    age: 2, cost: { food: 55, gold: 25 },
    trainTime: 17,
    color: '#ff6600',
    shape: 'square',
    description: 'Franks unique unit. Ranged infantry.',
    civOnly: 'franks',
    projectile: true,
  },
  battering_ram: {
    name: 'Battering Ram',
    icon: '&#128641;',
    hp: 200, attack: 40, meleeArmor: 5, pierceArmor: 5,
    range: 1, speed: 0.6, attackSpeed: 5.0, los: 3,
    age: 2, cost: { wood: 160, gold: 75 },
    trainTime: 56,
    color: '#885533',
    shape: 'rect',
    description: 'Siege unit, anti-building.',
    vsBuildingBonus: 5,
  },
  mangonel: {
    name: 'Mangonel',
    icon: '&#128641;',
    hp: 50, attack: 40, meleeArmor: 0, pierceArmor: 6,
    range: 7, minRange: 3, speed: 0.5, attackSpeed: 6.0, los: 7,
    age: 2, cost: { wood: 160, gold: 135 },
    trainTime: 46,
    color: '#664422',
    shape: 'rect',
    description: 'Siege unit, area damage.',
    aoe: 1.5,
    projectile: true,
  },
};

// Building stat definitions
const BUILDING_DEFS = {
  town_center: {
    name: 'Town Center',
    icon: '&#127968;',
    hp: 2400, size: 4,
    cost: { wood: 275 },
    buildTime: 150,
    age: 0,
    produces: ['villager'],
    dropOff: ['food', 'wood', 'gold', 'stone'],
    popCap: 5,
    los: 8,
    color: '#8866aa',
    description: 'Main building. Train villagers, age up.',
  },
  house: {
    name: 'House',
    icon: '&#127968;',
    hp: 550, size: 2,
    cost: { wood: 25 },
    buildTime: 25,
    age: 0,
    popCap: 5,
    color: '#775533',
    description: 'Increases population cap by 5.',
  },
  mill: {
    name: 'Mill',
    icon: '&#127806;',
    hp: 900, size: 3,
    cost: { wood: 100 },
    buildTime: 40,
    age: 0,
    dropOff: ['food'],
    color: '#aaaa44',
    description: 'Food drop-off point.',
  },
  lumber_camp: {
    name: 'Lumber Camp',
    icon: '&#129683;',
    hp: 600, size: 2,
    cost: { wood: 100 },
    buildTime: 35,
    age: 0,
    dropOff: ['wood'],
    color: '#665533',
    description: 'Wood drop-off point.',
  },
  mining_camp: {
    name: 'Mining Camp',
    icon: '&#9935;',
    hp: 600, size: 2,
    cost: { gold: 0, wood: 100 },
    buildTime: 35,
    age: 0,
    dropOff: ['gold', 'stone'],
    color: '#888877',
    description: 'Gold and stone drop-off point.',
  },
  farm: {
    name: 'Farm',
    icon: '&#127807;',
    hp: 360, size: 3,
    cost: { wood: 60 },
    buildTime: 15,
    age: 0,
    foodSource: true,
    foodRate: 0.3, // food per second while worked
    color: '#88aa44',
    description: 'Provides slow food when worked by villager.',
  },
  barracks: {
    name: 'Barracks',
    icon: '&#9876;',
    hp: 1200, size: 3,
    cost: { wood: 175 },
    buildTime: 50,
    age: 1,
    produces: ['militia', 'man_at_arms'],
    color: '#994433',
    description: 'Train infantry units.',
  },
  archery_range: {
    name: 'Archery Range',
    icon: '&#127996;',
    hp: 1200, size: 3,
    cost: { wood: 175 },
    buildTime: 50,
    age: 1,
    produces: ['archer', 'crossbowman', 'longbowman'],
    color: '#998833',
    description: 'Train archer units.',
  },
  stable: {
    name: 'Stable',
    icon: '&#128014;',
    hp: 1500, size: 4,
    cost: { wood: 175 },
    buildTime: 50,
    age: 1,
    produces: ['scout', 'knight'],
    color: '#885522',
    description: 'Train cavalry units.',
  },
  castle: {
    name: 'Castle',
    icon: '&#9962;',
    hp: 4800, size: 4,
    cost: { stone: 650 },
    buildTime: 200,
    age: 2,
    produces: ['longbowman', 'throwing_axeman'],
    los: 10,
    attackRange: 8,
    attackDamage: 11,
    attackSpeed: 2.0,
    color: '#998888',
    description: 'Fortress. Train unique units.',
  },
  siege_workshop: {
    name: 'Siege Workshop',
    icon: '&#128641;',
    hp: 1500, size: 3,
    cost: { wood: 200 },
    buildTime: 40,
    age: 2,
    produces: ['battering_ram', 'mangonel'],
    color: '#776655',
    description: 'Train siege weapons.',
  },
  tower: {
    name: 'Watch Tower',
    icon: '&#9961;',
    hp: 1000, size: 2,
    cost: { wood: 125, stone: 100 },
    buildTime: 80,
    age: 1,
    attackRange: 7,
    attackDamage: 5,
    attackSpeed: 2.0,
    los: 8,
    color: '#997755',
    description: 'Defensive tower.',
  },
  wall: {
    name: 'Stone Wall',
    icon: '&#9632;',
    hp: 1800, size: 1,
    cost: { stone: 5 },
    buildTime: 10,
    age: 1,
    color: '#aaaaaa',
    description: 'Defensive wall segment.',
  },
};

// Age definitions
const AGE_DEFS = [
  {
    name: 'Dark Age',
    advanceCost: null,
    advanceTime: 0,
  },
  {
    name: 'Feudal Age',
    advanceCost: { food: 500 },
    advanceTime: 130,
  },
  {
    name: 'Castle Age',
    advanceCost: { food: 800, gold: 200 },
    advanceTime: 160,
  },
];

// Apply civ bonuses to unit stats
function applyStatBonuses(unitType, stats, civName) {
  const civ = CIVS[civName];
  if (!civ) return stats;
  const s = Object.assign({}, stats);

  if (civName === 'franks' && (unitType === 'scout' || unitType === 'knight')) {
    s.hp = Math.round(s.hp * civ.bonuses.cavalryHPBonus);
  }
  return s;
}
